name: document

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write


jobs:
  document:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - name: Install system dependencies
      # required for Rfast
        run: sudo apt-get install -y libgomp1
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::roxygen2
          needs: pr-document

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: commit
        run: |
            git config --local user.name "$GITHUB_ACTOR"
            git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add man/\* NAMESPACE
            git diff --staged --quiet || git commit -m 'Automatic documentation'
            git pull --ff-only
            git push origin
